/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LoginSystem;

import dinal.appleistore3.CSVHandler;
import dinal.appleistore3.employee.ManagerUI;
import dinal.appleistore3.product.StockerUI;
import dinal.appleistore3.product.ViewProductsUI;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author dnlx
 */
public class LoginFormUI extends javax.swing.JFrame {

    /**
     * Creates new form LoginFormUI
     */
    public LoginFormUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        empPF = new javax.swing.JPasswordField();
        empNameTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LoginBT = new javax.swing.JButton();
        ClearBT2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        loginErrorTP = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(100, 100));
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        empPF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(empPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 221, -1));

        empNameTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(empNameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 221, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 51, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Password");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 80, -1));

        LoginBT.setBackground(new java.awt.Color(204, 204, 255));
        LoginBT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LoginBT.setText("Login");
        LoginBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBTActionPerformed(evt);
            }
        });
        jPanel1.add(LoginBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, -1, -1));

        ClearBT2.setBackground(new java.awt.Color(204, 204, 255));
        ClearBT2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ClearBT2.setText("Clear");
        ClearBT2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearBT2ActionPerformed(evt);
            }
        });
        jPanel1.add(ClearBT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, -1, -1));

        jScrollPane1.setViewportView(loginErrorTP);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 220, -1));

        jLabel4.setText("@DinalHasantha");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("AppleiStore");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void LoginBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBTActionPerformed
        try {
            // TODO add your handling code here:
            //private static void addDataToEmpTable() throws FileNotFoundException {
            String empName = empNameTF.getText();
            String empPw = empPF.getText();
            ArrayList<String> employees = CSVHandler.read("./employee.csv");
            for (String employee : employees) {
                String[] employeeData = employee.split(",");
 //               System.out.println(employeeData[1]);
//                System.out.println(employeeData[2]);
//                System.out.println(employeeData[3]);
                if (employeeData[1].equals(empName) && employeeData[2].equals(empPw) && employeeData[3].equals("Manager")) {
                    //System.out.println("Login success");
                    ManagerUI managerUI = new ManagerUI();
                    managerUI.setVisible(true);
                    this.dispose();
                } else if (employeeData[1].equals(empName) && employeeData[2].equals(empPw) && employeeData[3].equals("Cashier")) {
                    ViewProductsUI viewProductsUI = new ViewProductsUI();
                    viewProductsUI.setVisible(true);
                    this.dispose();
                } else if (employeeData[1].equals(empName) && employeeData[2].equals(empPw) && employeeData[3].equals("Stocker")) {
                    StockerUI stockerUI = new StockerUI();
                    stockerUI.setVisible(true);
                    this.dispose();
                } else{
                    loginErrorTP.setText("Wrong Details please try again");
                }
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(LoginFormUI.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_LoginBTActionPerformed

    private void ClearBT2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearBT2ActionPerformed
        // TODO add your handling code here:
        empNameTF.setText("");
        empPF.setText("");
    }//GEN-LAST:event_ClearBT2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFormUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFormUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFormUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFormUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFormUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClearBT2;
    private javax.swing.JButton LoginBT;
    public javax.swing.JTextField empNameTF;
    private javax.swing.JPasswordField empPF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane loginErrorTP;
    // End of variables declaration//GEN-END:variables

    private static class logininfo {

        public logininfo() {
        }
    }
}
